# Generated by Django 3.0.6 on 2021-05-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210521_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentOrderedPost',
            fields=[
            ],
            options={
                'ordering': ['-date'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('posts.post',),
        ),
    ]
